# config
cover: /img/bg_img_sky.webp
logo: /img/logo.png
top_saying:
- title: Code Life Better
- content: 開發中
bottom_saying: Don't think, just do
# Content
excerpt_link: Read More

rss: /atom.xml

highlightjs: vs

#Works
works:
- works_name: AAA
  works_url: /
- works_name: BBB
  works_url: /atom.xml

#duoshuo name
duoshuo:

#disqus name
# disqus_shortname: hexo-darrelltw-site

#fancybox
fancybox: true

# Miscellaneous
github: https://github.com/Darrellwan
facebook: https://www.facebook.com/
darrell_news: https://news.darrelltw.com?utm_source=referral&utm_medium=darrelltw.com

#about  timeline
timeline:
- num: 1
  word: 2014/06/12-Start
- num: 2
  word: 2014/11/29-XXX
- num: 3
  word: 2015/02/18-DDD
- num: 4
  word: More

#Links
links:
- name: Kieran
  link: http://go.kieran.top/
- name: Name
  link: http://domain.com/

# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
  enable: false
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 2

gtm: true
