<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9673254310878253"
     crossorigin="anonymous"></script>
<!-- 多媒體-直立 -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-9673254310878253"
     data-ad-slot="6666744104"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>