name: GitHub Actions Demo
on: 
  push:
    branches:
      - "main"
  pull_request:
    branches: ["main"]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "? The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "? This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "? The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: hexo clean; hexo g;
      - run: echo "? This job's status is ${{ job.status }}."