name: Twitter Post on New Article

on:
  push:
    branches:
      - dev-action-new-x-post # 或者你使用的分支名
jobs:
  check-new-files:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check for New Files
      run: |
        # 取得最近兩次提交的 ID
        LAST_COMMIT=$(git rev-parse HEAD)
        SECOND_LAST_COMMIT=$(git rev-parse HEAD~1)

        # 列出在特定路徑下，這兩次提交間新增的文件
        git diff --name-only --diff-filter=A $SECOND_LAST_COMMIT $LAST_COMMIT -- './source/_posts/*.md'
      
