name: Webhook Post on New Article

on:
  push:
    branches:
      - main
    paths:
      - 'source/_posts/*.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  webhook-new-article:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: .

    - name: Debug Directory Structure
      run: |
        echo "GitHub Workspace: $GITHUB_WORKSPACE"
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo "Parent directory contents:"
        ls -la ..
        echo "Requirements.txt location attempt 1:"
        find . -name requirements.txt
        echo "Requirements.txt location attempt 2:"
        find $GITHUB_WORKSPACE -name requirements.txt

    - name: Create requirements.txt
      run: |
        echo "requests==2.31.0" > requirements.txt
        echo "PyYAML==6.0.1" >> requirements.txt
        echo "loguru==0.7.2" >> requirements.txt
        echo "python-dotenv==1.0.1" >> requirements.txt
        echo "Created requirements.txt with contents:"
        cat requirements.txt

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        cache: 'pip'
        cache-dependency-path: |
          requirements.txt

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check for New Markdown Files
      id: check-new-md-files
      run: |
        if [ $(git rev-list --count HEAD) -gt 1 ]; then
          # 使用 github.event 變數更精確地檢測變更
          NEW_FILES=$(git diff --name-only --diff-filter=A ${{ github.event.before || 'HEAD~1' }} ${{ github.sha }} -- './source/_posts/*.md')
          echo "New markdown files: $NEW_FILES"
          if [ -n "$NEW_FILES" ]; then
            echo "new_files=$NEW_FILES" >> $GITHUB_OUTPUT
            echo "new_files_py=$NEW_FILES" >> $GITHUB_ENV
            
            # 從檔名擷取文章 ID 以構建 URL
            for file in $NEW_FILES; do
              FILENAME=$(basename "$file" .md)
              echo "article_id=$FILENAME" >> $GITHUB_OUTPUT
              echo "article_id=$FILENAME" >> $GITHUB_ENV
              echo "Article ID: $FILENAME"
            done
            
            # 生成當前日期格式為 YYYYMMDD
            TODAY=$(date +"%Y%m%d")
            echo "post_date=$TODAY" >> $GITHUB_OUTPUT
            echo "post_date=$TODAY" >> $GITHUB_ENV
          fi
        else
          echo "Not enough commits to compare."
        fi

    - name: Process and Send Webhook
      if: steps.check-new-md-files.outputs.new_files
      run: |
        set -e  # 確保任何錯誤都會導致步驟失敗
        
        # 構建完整網址含 UTM 參數
        WEBSITE_URL="${{ secrets.WEBSITE_URL || 'https://www.darrelltw.com' }}"
        ARTICLE_ID="${{ steps.check-new-md-files.outputs.article_id }}"
        POST_DATE="${{ steps.check-new-md-files.outputs.post_date }}"
        FULL_URL="$WEBSITE_URL/$ARTICLE_ID/?utm_source=webhook&utm_medium=automation&utm_campaign=$POST_DATE"
        
        # 將 URL 傳遞給 Python 腳本
        export FULL_URL="$FULL_URL"
        echo "Article URL with UTM: $FULL_URL"
        
        python .github/scripts/webhook_article.py
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        WEBSITE_URL: ${{ secrets.WEBSITE_URL || 'https://www.darrelltw.com' }}
        ARTICLE_ID: ${{ steps.check-new-md-files.outputs.article_id }}
        POST_DATE: ${{ steps.check-new-md-files.outputs.post_date }}
    
    - name: Print Log File
      if: always()
      run: |
        if [ -f log.txt ]; then
          cat log.txt
        else
          echo "log.txt does not exist."
        fi
